export const INCREMENT     = 'INCREMENT'
export const DECREMENT     = 'DECREMENT'
export const ADD_FIVE      = 'ADD_FIVE'
export const REMOVE_FIVE   = 'REMOVE_FIVE'
export const STORE_RESULT  = 'STORE_RESULT'
export const DELETE_RESULT = 'DELETE_RESULT'