version: '3.6'

services:
  #backend api
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/back
    environment:
      POSTGRES_URI : postgres://thaumocracy:password@postgres:5432/smart-brain-docker
      REDIS_URI : redis://redis
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/smart-brain-api
  # Postgres DB
  postgres:    
    container_name: postgres
    environment:
      POSTGRES_USER: thaumocracy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports: 
      - "5432:5432"
  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    